cloud_download="cloud-download.svg"
dice="dice.svg"
enter="enter.svg"
trash="trash.svg"
fng="fng.svg"
fantasy_and_folklore="fantasynamegenerators/fantasy-and-folklore.svg"
other_names="fantasynamegenerators/other-names.svg"
places_and_locations="fantasynamegenerators/places-and-locations.svg"
pop_culture="fantasynamegenerators/pop-culture.svg"
real_names="fantasynamegenerators/real-names.svg"
